services:
  web:
    image: moshensky/lw:pixel-alchemist-vX.X.X
    environment:
      VIRTUAL_HOST: pixel-alchemist.moshensky.com
      LETSENCRYPT_HOST: pixel-alchemist.moshensky.com
      LETSENCRYPT_EMAIL: nikita@moshensky.com
    expose:
      - "80"
    networks:
      - frontend
    restart: always

networks:
  frontend:
    external: true
    name: nginx-proxy
